### ISSUE TITLE
Remove methods from the SessionHelper

### ISSUE THREAD

**Issue by heyapricot** [1ba1/members-only#2]
In rails, think of helpers as `view helpers`. Currently, a big part of your application's logic resides on the SessionsHelper. Move each method to its corresponding controller. Some hints:
- Find or find by shouldn't be called from a view
- If a method is going to be used by multiple controllers (current_user maybe?) define it on the application controller so all the controllers can inherit it

**Comment by JangkarBumi** [comment]
1. Can you explain a bit more about that? Because we are sure that we dont call the find method from the view.
2. Done

**Comment by heyapricot** [comment]
Sure. I think [this link](http://codefol.io/posts/where-do-i-put-my-code-in-rails-updated/) gives a good explanation. From the `Helpers` section:

Rails “helpers” are very specifically view helpers. They’re automatically included in views, but not in controllers or models. That’s on purpose.

Code in the application helper is included in all the views in your application. Code in other helpers is included in the corresponding view. If you find yourself writing big loops, method calls or other logic in the view but it’s clearly display logic, move it into a method in the helper.

Do you need something like a “controller helper” or “model helper”? You can put it in a parent class if that makes sense. Or you can put it into the /lib directory, or any of the alternate places for lib-type code (see below.)

**Comment by 1ba1** [comment]
We have moved all the methods from sessions helper to the application controller
and then just add the functions that are related to the post view, to posts helper.
